//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospitalApp.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CheckUp
    {
        public int id { get; set; }
        public string CheckType { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public System.DateTime CreateAt { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
