//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospitalApp.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.CheckUps = new HashSet<CheckUp>();
        }
    
        public int id { get; set; }
        [DisplayName("«·«”„ ")]
        [Required(ErrorMessage = "Â–« «·Õﬁ· «Ã»«—Ì")]
        public string name { get; set; }
        [DisplayName("«·⁄„— ")]
        [Required(ErrorMessage = "Â–« «·Õﬁ «Ã»«—Ì")]
        public string age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckUp> CheckUps { get; set; }
    }
}
