//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospitalApp.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        public int id { get; set; }
        [DisplayName("«·«”„ ")]
        [Required(ErrorMessage ="Â–« «·Õﬁ· «Ã»«—Ì")]
        public string name { get; set; }
        [DisplayName("«·⁄„— ")]
        [Required (ErrorMessage ="Â–« «·Õﬁ «Ã»«—Ì")]
        public string age { get; set; }
    }
}
